ClusterName=homelab-marcoule
SlurmctldHost=k3s-node
SlurmUser=slurm
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmctldPort=6817
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld
AuthType=auth/munge
CryptoType=crypto/munge
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldDebug=info
SlurmdDebug=info
JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30
NodeName=k3s-node CPUs=3 RealMemory=8192 State=UNKNOWN
PartitionName=batch Nodes=k3s-node Default=YES MaxTime=INFINITE State=UP
PartitionName=debug Nodes=k3s-node Default=NO MaxTime=00:30:00 State=UP
